name: 'Bug Report'
description: 'Create a bug report to help us improve'
title: '[BUG]'
labels: bug
assignees: []
body:
  - type: markdown
    attributes:
      value: Thank you for reporting an issue.
        Please fill in as much of the form below as you're able to.
  - type: textarea
    attributes:
      label: Issue Description
      description: Please provide a clear and concise description of the problem.
      validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue. Include code snippets, error messages, and any other relevant information.
      validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      validations:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: Other information
  - type: textarea
    attributes:
      label: Screenshots (optional)
      description: If applicable, add screenshots to help explain the issue.
  - type: input
    attributes:
      label: Operating System [e.g., Windows 10]
  - type: input
    attributes:
      label: Browser [e.g., Chrome, Firefox]
  - type: input
    attributes:
      label: nodejs-version [e.g. v20.15.0]
  - type: checkboxes
    attributes:
      label: Please check the boxes that apply to this issue report.
      options:
        - label: I have searched the existing issues to make sure this is not a duplicate.
        - label: I have provided steps to reproduce the issue.
        - label: I have included relevant environment information.
        - label: I have included any relevant screenshots.
